/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockGovernance } from "./MockGovernance";
export * as factories from "./factories";
export { MockGovernance__factory } from "./factories/MockGovernance__factory";
